### ISSUE TITLE
Not Working on Next.js

### ISSUE THREAD

**Issue by karim-hammami** [maniyedidi/react-json-to-excel#1]
i was using it on a project and got
`
TypeError: window.XLS is undefined
`
after a bit of digging around i discovered that it comes from
`
const ws = window.XLS.utils.json_to_sheet(data);
`

my guess is since Next.js is dynamic and requires a server to run so it doesn't include index.html in the source directory it only serves html on build

**Comment by maniyedidi** [comment]
Issue is fixed now in v1.0.5
