### ISSUE TITLE
Update react version to v18

### ISSUE THREAD

**Issue by aditodkar** [maniyedidi/react-json-to-excel#2]
I am using this package in nextjs project. But react-json-to-excel forces react v17 which is incompatible with nextJs v13. If possible can we update react version?

Screenshot: 
![image](https://user-images.githubusercontent.com/16613832/215269854-9d4cc94b-df93-42ef-94b2-2f942dbcbdd5.png)

**Comment by ghost** [comment]
Any progress on this?

**Comment by DeeTechPubs** [comment]
Is this going to get fixed?

**Comment by autrioly** [comment]
any alternative to this ?

**Comment by keo4041** [comment]
I'm in the same boat

**Comment by maniyedidi** [comment]
Updated to react 18
